name: project1
on:
  push:
  workflow_dispatch:
jobs:
  myfirstjob_cicd:
     runs-on: ubuntu-latest
     steps:
        - name: checkout code
          uses: actions/checkout@v5
        - name: setup java with maven
          uses: actions/setup-java@v5
          with:
           distribution: 'temurin'
           java-version: '21'
           cache: 'maven'
        - name: run the piprline from the lab
          uses: cross-the-world/ssh-scp-ssh-pipelines@latest
          with:
             host: '65.2.36.121'
             user: 'labuser'
             pass: 'Nuvelabs123$'
             port: 22
             connect_timeout: 10s
             first_ssh: |
                 sudo curl -l -u admin:Root123$ http://localhost:8080/job/deploy_jenkinsfile_demo/build?token=token_balu
        - name: list the files
          run: |
            cd ./target
            ls -l
